### ISSUE TITLE
KiNG does not display some Hydrogens

### ISSUE THREAD

**Issue by russell-taylor** [rlabduke/javadev#2]
When the CCTBX tool mmtbx.hydrogenate is used to place hydrogens on a 4fen.pdb, it names the hydrogens that are attached to C5' as H5*1 and H5*2. The original reduce named them H5' and H5''. One example is C5' C B 80.

KiNG shows them when they are named H5' and H5'' but not when they are named H5*1 and H5*2. Just renaming them in the output file makes them show up, so this is not a geometry issue.

It looks like the atom-parsing code is not sufficiently general.

**Comment by dcrrlab** [comment]
The H51 and H52 names are VERY old (I think v2.7, pre 2007) and the H5' and H5'' (two primes, not a double-prime) are pretty awful, but they are the legal names.   Also, most methylene H pairs are now 2 and 3, not 1 and 2, since v3.  There's only one legal set of names at a given time.  We still check for v2.7 names and correct them on MolProbity input, but I haven't seen that happen in a long time.
     All the names were still v2.7 in Phenix until pretty recently.  Supposedly Nigel finally fixed them a couple of years ago, but maybe missed this oddball, non-protein case.  Or maybe this is an unfortunate version control problem.  But it's almost certainly not unique to 4fen.  I'm glad it wasn't a geometry issue.

Jane

Richardson Lab
132 Nanaline Duke Bldg.
Duke U Med Ctr 3711
Durham NC 27710, USA
1-919-684-6010; fax 684-8885
***@***.***
________________________________
From: Russell Taylor ***@***.***>
Sent: Friday, August 4, 2023 5:55 PM
To: rlabduke/javadev ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rlabduke/javadev] KiNG does not display some Hydrogens (Issue #2)


When the CCTBX tool mmtbx.hydrogenate is used to place hydrogens on a 4fen.pdb, it names the hydrogens that are attached to C5' as H51 and H52. The original reduce named them H5' and H5''.

KiNG shows them when they are named H5' and H5'' but not when they are named H51 and H52. Just renaming them in the output file makes them show up, so this is not a geometry issue.

It looks like the atom-parsing code is not sufficiently general.

**Comment by russell-taylor** [comment]
Closing as not a bug.
